godotengine/godot-cpp-template

demo/bin/example.gdextension
Without quotes the values is parsed as a float, breaking in various cases.
* See: https://github.com/godotengine/godot-cpp/pull/1226
=> Fix formatting of `compatibility_minimum`

.github/workflows/builds.yml
Counterpart to https://github.com/godotengine/godot-cpp/pull/1259.
=> CI: Pin MinGW version to 12.2.0 to fix install issue

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
=> Fix GitHub issue template not being parsed as form

.gitignore, SConstruct
As the title says, it adds compiledb and custom.py support.
This is needed for new users for the process to be as smooth as possible. This includes the generation of compile_commands.json to enable autocompletion while creating C++ code.
Depends on https://github.com/godotengine/godot-cpp/pull/1220
**Edit:** Added help support too
=> Add compiledb, help and custom.py support

SConstruct
Use InstallAs with the correct target/source order instead of Command.
Closes #19 
Fixes #17
=> Fix library copy command

.github/actions/build/action.yml, .github/actions/sign/action.yml, .github/workflows/builds.yml, .gitignore, README.md, bin/ios/Info.plist, bin/macos/macos.framework/Resources/Info.plist
Added an action that can build everything and that can be called from outside. Added info on how to use from readme. Added a sign action.
- Fixes https://github.com/godotengine/godot-proposals/issues/8579
=> Add more stuff/options to build

.github/actions/build/action.yml, .github/workflows/builds.yml
- Add target-type in builds to let users customize what build type they want to make (`target_release` or `target_debug`)
- Fix android builds using old sdk
- Fix artifact upload issue by uploading artifacts separately and then merging the artifacts
Closes #31 (Builds on PR #33)
Closes #30
=> Fix android builds, improved flexibility of matrix builds, fix artifact upload

SConstruct, methods.py
This makes the error that is printed easier to understand, with a command given as a solution to run.
The error message is also colored to match how core Godot displays this kind of build errors.
=> Print an error if the godot-cpp submodule hasn't been initialized

README.md
v3 has been deprecated for a while, and the bump to v4 is painless (and has been done on the action itself already).
=> In the readme suggested action, use checkout and upload-artifact v4.

README.md
Follow-up of #45. I forgot that upload-artifact v4 doesn't support auto-merging. Sorry!
=> Update README.md to include a merge step, separating platform uploads

SConstruct
Note: Superseded by #49.
Right now, it places the file into `demo/bin/libmacos.framework/<name>.macos.template_debug`, which is not wanted.
=> Fix macos demo build target in SConstruct

.github/actions/build/action.yml
This flag prints a warning about being unrecognized to the action. If someone actually were to define the flag, this also could cause problems.
=> Remove invalid production=yes flag from github action

.gitignore
This adds a line to `.gitignore` to ignore the files generated for documentation.
=> Ignore files generated for documentation

.github/actions/build/action.yml
As per https://github.com/godotengine/godot/pull/96610
we now use 3.1.62 in godotengine so we should align them
=> Update emscripten to the version used by godotengine - 3.1.62

.github/workflows/builds.yml, README.md
This slightly speeds up the checkout. Setting fetch-depth to 0 fetches all branches and tags, which should not be required.
=> Reset github checkout fetch-depth to 1.

SConstruct
I found that the compiledb parameter option in SConstruct may be redundant, because the game project is build together with godot-cpp, and there are already related builds and parameters for compiledb in godot-cpp.
So I removed the parameters of computedb and kept an example argument in its place as a replacement.
=> Clean up unnecessary compiledb parameters

.github/actions/build/action.yml
This does several things:
- It actually publishes / fixes the parameters, intended for different folder setups of the project.
- godot-cpp is actually built now, as intended by the action author.
- I'm not sure if we even need to, given that the latter command builds it fine. But that's for another PR to decide.
- It fixes scons caches, making builds a lot faster (I tested this; repeated builds now fly by very fast).
- It fixes a build error on windows when compiling with doc data.
=> Fix github action paths / parameters

.github/actions/build/action.yml
Briefly discussed on Rocket Chat, it seems this is wholly just not needed for the runner, as godot-cpp is built as part of the GDExtension build step.
I know some repositories suggest building the deps first and the project later, using separate caches for each such that a rebuild can go faster. But as far as I've seen, in this project it doesn't work because the later build step just re-builds godot-cpp from scratch anyhow (at least for me). If anybody's seen evidence to the contrary, please share them.
=> Remove unneeded godot-cpp build step from the GitHub action.

.github/actions/build/action.yml
I've been running into issues when multiple runners attempt to use the emsdk cache because the key is the same.
This has been addressed in v14: https://github.com/mymindstorm/setup-emsdk/releases/tag/v14
There should be no reason not to upgrade.
Edit: I tested my branch, builds work fine.
=> Update setup-emsdk from v13 to v14

.github/workflows/builds.yml
This mimics [Godot](https://github.com/godotengine/godot/blob/master/.github/workflows/runner.yml#L2) and [godot-cpp](https://github.com/godotengine/godot-cpp/blob/master/.github/workflows/runner.yml#L2) behavior, and should improve our ability to be confident about PRs not breaking stuff.
=> Run the github runner on pull requests and for merge groups automatically.

SConstruct, bin/ios/ios.framework/Info.plist, bin/macos/macos.framework/Resources/Info.plist, demo/bin/example.gdextension
Fixes #76
This adds the whole suffix instead of just the platform and target to the binary names.
https://github.com/godotengine/godot-cpp-template/blob/3b48c096840568cdd8dee94c6d0330a850d618fc/SConstruct#L51-L53
Here is the effect on the file names for macOS:
Before:
```
Resources
libEXTENSION-NAME.macos.template_debug
```
After:
```
Resources
libEXTENSION-NAME.macos.template_debug.double.universal
libEXTENSION-NAME.macos.template_debug.universal
```
Requires adjustment to `Info.plist` files.
Also fixes the `CFBundleExecutable` pointing to a macOS framework for iOS. https://github.com/godotengine/godot-cpp-template/commit/3b48c096840568cdd8dee94c6d0330a850d618fc#diff-38bc16d5822bfc5e55a99774078b8f4612d6936342a53059e42ee74bd5fd0661R10
=> Include env["suffix"] in binary names for macOS and iOS

.github/workflows/builds.yml
Instead of having a code block for every possible build combination this PR uses the proper matrix notation to reduce the length of the file and improve readability. I made sure to not change the actual configuration of builds that are being produced. Though I'm not sure why its setup to run all the `double` builds since those aren't linked to in the `.gdextension` file.
```yml
- platform: linux
float-precision: single
arch: x86_64
target-type: template_debug
os: ubuntu-20.04
- platform: windows
float-precision: single
arch: x86_32
target-type: template_debug
os: windows-latest
- platform: windows
float-precision: single
arch: x86_64
target-type: template_debug
os: windows-latest
```
becomes
```yml
target:
[
{ platform: linux, arch: x86_64, os: ubuntu-24.04 },
{ platform: windows, arch: …
```
=> Use matrix notation in build.yml to reduce clutter and update Ubuntu image

.github/workflows/builds.yml
This PR switches out the existing cache step with the [`godot-cache-restore`](https://github.com/godotengine/godot-cpp/blob/f3a1a2fd458dfaf4de08c906f22a2fe9e924b16f/.github/actions/godot-cache-restore/action.yml) and [`godot-cache-save`](https://github.com/godotengine/godot-cpp/blob/f3a1a2fd458dfaf4de08c906f22a2fe9e924b16f/.github/actions/godot-cache-save/action.yml) actions from godot-cpp. These actions have a different scheme for the cache keys. They create a new cache for every commit by appending - among other things - the commit SHA, but restore from any key that matches up until the unique identifier. Using this approach fixes the caches not being updatable.
A few notes:
- GODOT_BASE_BRANCH doesn't seem to be set, so there is one empty part. Where is this set normally?
- I dropped …
=> CI: Use caching actions from godot-cpp

SConstruct, build_profile.json
I suggest adding this file to hint at the fact that doing this is possible. Disabling unused classes can save a lot of time when compiling godot-cpp.
The included build profile has some example classes enabled. To make use of the feature, a user would discover the file, read the comment in the SConstruct, adjust the profile and uncomment the instruction.
=> Add an example for using a build profile

.github/workflows/builds.yml
Fixes #88:
- Adds `linux x86_32`, `linux arm64`, `linux arm32`, `windows arm64`, `template_release` for non-`linux` builds
- Rearranges builds for consistency
- Fixes spelling error
- Adds trailing comma to make it easier to add new items
I chose the architectures from the "all downloads" dropdown available at [Godot 4.4.1-stable](https://godotengine.org/download/archive/4.4.1-stable).
Notes from my research:
- Windows does not support `arm32`.
- iOS does not support `x86_64` or `x86_32`, and does not use `arm32` since iPhone 5 (2012).
- `wasm64` exists but is experimental and not supported by the compiler.
**Possible issues:**
I have been having issues with `linux x86_32` and `linux arm64` in my personal project:
I get this error with `x86_32`:
```
Compiling godot-cpp/src/core/memory.cpp …
```
=> Improve workflow architectures

demo/example.gd, demo/example.tscn, doc_classes/ExampleClass.xml, src/example_class.cpp, src/example_class.h, src/register_types.cpp
When you first clone `godot-cpp-template`, you may still have no idea what to do next, because the gdextension doesn't actually do anything right now. This may be additionally confusing because you may not know how to check your GDExtension is even loading.
While the docs explain how to create and register classes, people may not look there when starting a project. It's may be easier to have some boilerplate for it ready and get right to programming C++.
This PR adds a minimal class for example purposes. I don't think we should try to cover a lot of functionality with it, but a single registered function and some docs is probably enough for people to kick off their project from.
=> Add an example class to the project.

.editorconfig, .gitignore, CMakeLists.txt
Adds a CMakeLists that builds against 4.4
=> Add CMake file

README.md
Supersedes https://github.com/godotengine/godot-cpp-template/pull/91
Adds a section explaining that a compilation database can be compiled using scons to enable IDE features like autocomplete and more.
=> Add section about LSP support by compiledb scons command
